version: "3"
services:
  book_catalog:
    build:
      context: ./book_catalog
    container_name: book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_k8g1_user:DwhykqXbtbSk5dJEVKpgg2f5V4NnPeD8@dpg-cs191hq3esus739c798g-a.singapore-postgres.render.com/sit722_k8g1

  inventory_management:
    build:
      context: ./inventory_management
    container_name: inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_k8g1_user:DwhykqXbtbSk5dJEVKpgg2f5V4NnPeD8@dpg-cs191hq3esus739c798g-a.singapore-postgres.render.com/sit722_k8g1
