version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8010:8010"
    environment:
      - PORT=8011
      - DATABASE_URL=postgresql://part3_9s6m_user:eFkkxKo31o996A8tioQNMWCny4SyJHbW@dpg-cra8795ds78s73cqccf0-a.oregon-postgres.render.com/part3_9s6m
    restart: "no"

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8012:8012"
    environment:
      - PORT=8012
      - DATABASE_URL=postgresql://sit722_icdp_user:gKkEmcjvzFXgr2AJwkkGmSbENzWQpl8J@dpg-cs0tnbe8ii6s73ctnaig-a.oregon-postgres.render.com/sit722_icdp
    restart: "no"
